export * from './get_analista'
export * from './create_analista'
export * from './get_analista_by_num_cl'
export * from './get_analista-by-id'
export * from './get_analista_by_grado'
export * from './get_analistas_by_id_unidad'