export * from './DatosGenerales'
export * from './ResumenCaso'
export * from './Detenido'
export * from './Armas'
export * from './Vehiculos'
export * from './Dinero'
export * from './SustanciasSujetasF'
export * from './ReporteApoyoTecnico'
export * from './Anexos'

export * from './Municiones'