export * from './DatosGenerales'
export * from './ResumenCaso'
export * from './Detenido'
export * from './Armas'
export * from './Vehiculo'
export * from './Dinero'
export * from './sustancias-ilegales'